---
abstract: 'Export a CSV file to MySQL.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-CSV-Auto-ExportTo-MySQL
requires:
  DBD::mysql: 4.018
  Moose: 1.24
  Text::CSV::Auto: 0.06
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-CSV-Auto-ExportTo-MySQL
  repository: git://github.com/bluefeet/Text-CSV-Auto-ExportTo-MySQL.git
version: 0.02
